[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.3"

[features]
seeds = false
skip-lint = false

[programs.devnet]
jogo_program = "dqbxjMuubFQjkpMdRPC1a9CwVfFMwsRJMKnnXemYNVk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = ".keypairs/deployer.json"

[scripts]
deposit = "yarn ts-node app/deposit.ts"
init_admin = "yarn ts-node app/init_admin.ts"
init_crash_bet = "yarn ts-node app/create_crash_bet.ts"
init_crash_game = "yarn ts-node app/init_crash_game.ts"
init_randomness = "yarn ts-node app/create_randomness.ts"
init_vault = "yarn ts-node app/init_vault.ts"
lock_crash = "yarn ts-node app/new_crash_game.ts"
settle_crash = "yarn ts-node app/settle_crash_game.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
