[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.3"

[features]
seeds = false
skip-lint = false

[programs.devnet]
jogo_program = "9FLyauM11S1SRwM5kxNUYTYJMbrxdt41dYQF1bZHqcoP"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = ".keypairs/deployer.json"

[scripts]
init_vault = "yarn init_vault"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
