[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.3"

[features]
seeds = false
skip-lint = false

[programs.devnet]
jogo_program = "9Efg64Ztcb2qzN5Pyq6yk3hBSUwCZVzfLdtCcZ7RnzJw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = ".keypairs/deployer.json"

[scripts]
crash_create_bet = "yarn ts-node app/crash/create_bet.ts"
crash_lock_game = "yarn ts-node app/crash/lock_game.ts"
crash_request_random = "yarn ts-node app/crash/request_random.ts"
crash_settle_bet = "yarn ts-node app/crash/settle_bet.ts"
exchange_mint_chip = "yarn ts-node app/exchange/mint_chip.ts"
exchange_swap_in = "yarn ts-node app/exchange/swap_in.ts"
exchange_swap_out = "yarn ts-node app/exchange/swap_out.ts"
init_admin = "yarn ts-node app/init_admin.ts"
init_crash_game = "yarn ts-node app/crash/init_game.ts"
init_exchange = "yarn ts-node app/exchange/init_exchange.ts"
init_vault = "yarn ts-node app/vault/init_vault.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
vault_deposit = "yarn ts-node app/vault/deposit.ts"
vault_withdraw = "yarn ts-node app/vault/withdraw.ts"
