[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.3"

[features]
seeds = false
skip-lint = false

[programs.devnet]
jogo_program = "8PqrU7ZDc66JcrwiexCqEavjeZMYBoR9ySFdXQZQgAUw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://jogojogo-dev2b46-932d.devnet.rpcpool.com/63e7440c-e69c-4b29-9b03-d7264f361209"
wallet = ".keypairs/deployer.json"

[scripts]
create_crash_bet = "yarn ts-node app/create_crash_bet.ts"
deposit_and_withdraw = "yarn ts-node app/deposit_and_withdraw.ts"
init_admin = "yarn ts-node app/init_admin.ts"
init_crash_game = "yarn ts-node app/init_crash_game.ts"
init_vault = "yarn ts-node app/init_vault.ts"
lock_crash_game = "yarn ts-node app/lock_crash_game.ts"
request_randomness = "yarn ts-node app/request_randomness.ts"
settle_crash_game = "yarn ts-node app/settle_crash_game.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
