[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.3"

[features]
seeds = false
skip-lint = false

[programs.devnet]
jogo_program = "FHcfAFsrp1Y4i1U4RCoDSbbRBCtvnpkcyvVYgc5J5jc4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = ".keypairs/deployer.json"

[scripts]
deploy_jogo = "anchor deploy --program-name=jogo_program --program-keypair=target/deploy/jogo_program-keypair.json"
init_vault = "yarn init_vault"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
