[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.3"

[features]
seeds = false
skip-lint = false

[programs.devnet]
sports-program = "HjEBMq4XX5uw6HHULUUvHderJagW6jQf5fVgGuBNFian"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = ".keypairs/deployer.json"

[scripts]
init_admin = "yarn ts-node app/admin/init_admin.ts"
assign_operator = "yarn ts-node app/admin/assign_operator.ts"
init_club = "yarn ts-node app/sports/init_club.ts"
close_club = "yarn ts-node app/sports/close_club.ts"
deposit = "yarn ts-node app/sports/deposit.ts"
withdraw = "yarn ts-node app/sports/withdraw.ts"
bet = "yarn ts-node app/sports/bet.ts"
cancel_bet = "yarn ts-node app/sports/cancel_bet.ts"
settle = "yarn ts-node app/sports/settle.ts"