[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.20"

[features]
seeds = false
skip-lint = false

[programs.localnet]
jogo_program = "G4pgWxx2YTE2rGezW3cULwbAruCjh1TNYTu2Df6HCVP2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/geyunlong/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
