[toolchain]
anchor_version = "0.29.0"
solana_version = "1.18.3"

[features]
seeds = false
skip-lint = false

[programs.devnet]
sports-program = "KRXNJkATAMf7B8ZGrNaVpu6FjvQWxfghqce6mquRcQQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=84bb7591-c544-4b27-9810-0888467759fe"
wallet = ".keypairs/deployer.json"

[scripts]
init_admin = "yarn ts-node app/admin/init_admin.ts"
assign_operator = "yarn ts-node app/admin/assign_operator.ts"
init_club = "yarn ts-node app/game/init_club.ts"
deposit = "yarn ts-node app/game/deposit.ts"
withdraw = "yarn ts-node app/game/withdraw.ts"
bet = "yarn ts-node app/game/bet.ts"
settle = "yarn ts-node app/game/settle.ts"