[package]
name = "vault-program"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "vault_program"

[dependencies]
anchor-lang = { version = "0.29.0", features = ["derive", "init-if-needed", "event-cpi"] }

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []